name: Build & Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build and release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          ALLOW_ELECTRON_BUILDER_AS_PRODUCTION_DEPENDENCY: true
        with:
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          github_token: ${{ secrets.GH_TOKEN }}
          use_vue_cli: true
